trigger:
  branches:
    exclude:
    - '*'
  paths:
    include:
    - 'path/to/your/heartbeat_base_xlsx_template_copy_2.xlsx'

jobs:
- job: RunPythonScript
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - checkout: self  # Add a checkout step to get the latest code
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      addToPath: true
  - script: |
      pip install -r requirements.txt
      python main_run02.py


- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
