trigger:
  branches:
    exclude:
    - '*'
  paths:
    include:
    - 'heartbeat base xlsx template_copy(2).xlsx'

jobs:
- job: RunPythonScript
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      addToPath: true
  - script: |
      pip install -r requirements.txt
      python main_run02.py


